name: online_sessions
description: "Managing online sessions for VTTs."
version: 1.4.2
homepage:

publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^6.1.2
  cloud_functions: ^6.0.6
  collection: ^1.17.0
  crypto: ^3.0.6
  equatable: ^2.0.7
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  google_sign_in: ^7.1.1
  hydrated_bloc: ^10.0.0
  logging: ^1.0.2
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.1.7
  flutter_gen: ^5.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  json_annotation: ^4.9.0
  json_serializable: ^6.1.6
  mocktail: ^1.0.0
  source_gen: ^4.2.0

flutter:
